# Generated by Django 6.1 on 2026-08-10 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Fiction', 'Fiction'), ('Sci-Fi', 'Sci Fi'), ('Biography', 'Biography'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Horror', 'Horror')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('published_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
